// ============================================================
// adc_reader.sv — MAX 10 Internal ADC Interface Wrapper
// CrashTech VLSI-2026 — Challenge 5: FPGA Volt-Meter
// ============================================================
// Wraps the Altera Modular ADC Core IP (modular_adc_0).
//
// ADC HARDWARE FACTS:
//   • MAX 10 built-in 12-bit SAR ADC
//   • Internal 2.5 V VREF → input range 0 V – 2.5 V
//   • Arduino header A0 → ADCIN1 (channel 1) inside MAX 10
//   • ADC clock must be exactly 10 MHz (supplied by pll_10m)
//
// IP GENERATION — ONE-TIME SETUP IN QUARTUS:
//   1. Tools → IP Catalog, search "Modular ADC Core"
//   2. New Component name: modular_adc_0
//   3. Save to: fpga/ip/modular_adc_0/
//   4. Settings:
//        • Device family      : MAX 10
//        • ADC mode           : Single-ended
//        • ADC instance       : ADC1
//        • Analog input       : ADCIN1  (= Arduino A0)
//        • Number of channels : 1
//        • External clock     : YES  (we supply 10 MHz from pll_10m)
//        • Sequencer mode     : Standard
//   5. Click Generate HDL → add modular_adc_0.qip to the project
//   6. In fpga_voltmeter.qsf, uncomment the QIP_FILE line
//
// PORTS:
//   clk        — 50 MHz system clock
//   rst_n      — active-low reset (async assert, sync deassert)
//   clk_adc    — 10 MHz ADC clock from pll_10m
//   pll_locked — PLL lock flag (hold ADC in reset until locked)
//   adc_raw    — latest 12-bit ADC sample (registered)
//   adc_valid  — 1-cycle pulse whenever a new sample is captured
// ============================================================

module adc_reader (
    input  logic        clk,
    input  logic        rst_n,
    input  logic        clk_adc,
    input  logic        pll_locked,
    output logic [11:0] adc_raw,
    output logic        adc_valid
);

    // ---- Internal reset: hold ADC in reset until PLL locks ----
    logic rst_adc_n;
    assign rst_adc_n = rst_n & pll_locked;

    // ---- Avalon-ST Command interface (this module → ADC IP) ----
    logic        cmd_valid;
    logic [4:0]  cmd_channel;
    logic        cmd_sop;
    logic        cmd_eop;
    logic        cmd_ready;     // input from ADC IP

    // ---- Avalon-ST Response interface (ADC IP → this module) ----
    logic        rsp_valid;
    logic [4:0]  rsp_channel;
    logic [11:0] rsp_data;
    logic        rsp_sop;
    logic        rsp_eop;

    // ---- Modular ADC Core IP instantiation ----
    // Module 'modular_adc_0' is generated by Quartus IP Catalog.
    // Port names match the Quartus 17.1 Modular ADC Core output.
    modular_adc_0 u_adc (
        .clock_clk                  (clk),
        .reset_sink_reset_n         (rst_adc_n),
        .adc_pll_clock_clk          (clk_adc),
        .adc_pll_locked_export      (pll_locked),
        // Command
        .command_valid              (cmd_valid),
        .command_channel            (cmd_channel),
        .command_startofpacket      (cmd_sop),
        .command_endofpacket        (cmd_eop),
        .command_ready              (cmd_ready),
        // Response
        .response_valid             (rsp_valid),
        .response_channel           (rsp_channel),
        .response_data              (rsp_data),
        .response_startofpacket     (rsp_sop),
        .response_endofpacket       (rsp_eop)
    );

    // ---- Continuous command driver ----
    // Keep issuing single-channel (ch1 = ADCIN1 = A0) conversion
    // requests. SOP=EOP=1 because each request is a single sample.
    assign cmd_valid   = pll_locked;   // gate commands until PLL is ready
    assign cmd_channel = 5'd1;         // channel 1 = ADCIN1 = Arduino A0
    assign cmd_sop     = 1'b1;
    assign cmd_eop     = 1'b1;

    // ---- Capture response ----
    // Filter by channel to be safe; ignore any stray responses.
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            adc_raw   <= 12'd0;
            adc_valid <= 1'b0;
        end else begin
            adc_valid <= 1'b0;   // default: no new sample this cycle
            if (rsp_valid && (rsp_channel == 5'd1)) begin
                adc_raw   <= rsp_data;
                adc_valid <= 1'b1;
            end
        end
    end

endmodule
